G20/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',views.Topiclist.as_view(),name='home'),
    path('topic/<int:pk>', views.TopicDetail.as_view(),name='detail')
   
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('G20.urls'))
]

G20/models.py
from django.db import models


TOPIC_TYPE =(
    ('key_features','Key Features'),
    ('topics','Topics Of Discussion'),
    ('people','Guests')
)

class Item(models.Model):
    Topic = models.CharField(max_length=1000, unique=True)
    description = models.CharField(max_length=2000, unique=False)
    topic_type = models.CharField(max_length=200, choices=TOPIC_TYPE,default='Key Features')
    image = models.ImageField(upload_to="G20/images",default="")

def __str__(self):
    return self.Title

G20/views.py
from typing import Any, Dict
from django.shortcuts import render
from django.views import generic
from .models import Item,TOPIC_TYPE


class Topiclist(generic.ListView):
    queryset = Item.objects.order_by("-description")
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context =super().get_context_data(**kwargs)
        context['titles'] = TOPIC_TYPE
        return context




class TopicDetail(generic.DetailView):
    model = Item
    template_name = "detail.html"

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <title>G20 Info</title>
        <style>

            img{
                border: solid 2px black;
                margin-left: 300px;
                margin-top: 100px;
                width: 1320px;
                height: 750px;
                
            }
        </style>
    </head>
    <body  style=" background: linear-gradient(to bottom, #c5954e, #ffffff, #b5e9b9);">
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                    <a class="navbar-brand" href="#"></a>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                         <span class="navbar-toggler-icon"></span>
                    </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                         <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="/admin">Admin</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block content %}
        {% endblock content %}

<!-- JavaScript Bundle with Popper -->
             <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    </body>
</html>

templates/detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <head>
            <style>
                p{
                height: 40px;
                margin-top: -5px;
                font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
                font-size: large;
                
            }
            </style>
        </head>
        <h1 class="pt-5">{{ item.Topic }}</h1>
        <p>{{ item.description }}</p>
    </div>
        <img src="/media/{{ item.image }}">
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <head>
        <style>
            p{
                color: rgb(90, 133, 150);
                height: 40px;
                margin-top: -5px;
                font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
                font-size: large;
                
            }
            h2{
                font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
            }
        </style>
    </head>
  <h1>G20 INFO</h1>
    <ul class="list-group list-group-flush">
        {% for title in titles %}
            <h2 class="pt-5">{{ title.1 }}</h2>
                {% for row in item_list %}
                    {% if row.topic_type == title.0 %}
                        <li class="list-group-item d-flex justify-content-between align-items-center border-0 pb-0">
                            <a href="{% url 'detail' row.pk %}"><h3>{{ row.Topic }}</h3></a>
                        </li>
                        <li class="list-group-item pt-0">
                            <p>{{ row.description }}</p>
                        </li>
                        {% endif %}
                {% endfor %}
        {% endfor %}
    </ul>
</div>
{% endblock content %}